version: '3'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
            - '3001:3001'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
    react:
        container_name: react
        restart: always
        build: ./client
        ports:
            - '3000:3000'